behaviors:
  MoonlanderAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 20480
      learning_rate: 0.0003
      learning_rate_schedule: linear
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    checkpoint_interval: 5000
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      memory:
        sequence_length: 128
        memory_size: 512
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
        network_settings:
          normalize: true
          hidden_units: 256
          num_layers: 2
    keep_checkpoints: 10
    max_steps: 100000000
    time_horizon: 4000
    summary_freq: 10000
env_settings:
  env_path: "/Users/victorbarbosa/git/UNITY Web/UnityMoonLander/Mac/App.app"
  base_port: 5005
  num_envs: 1
  num_areas: 1
  timeout_wait: 60
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
  worker_trainer_types: null
engine_settings:
  width: 250
  height: 250
  quality_level: 0
  time_scale: 50.0
  target_frame_rate: 60
  capture_frame_rate: 0
  no_graphics: true
  no_graphics_monitor: false
environment_parameters:
  currentLesson: 5
  maxHorizonatal: 4
  steps: 1
checkpoint_settings:
  run_id: ppo
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: true
  inference: false
  results_dir: results
torch_settings:
  device: cuda
debug: false

 