# Teste de validação de device
behaviors:
  MoonlanderAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 0.0003
      learning_rate_schedule: linear
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    checkpoint_interval: 1000
    network_settings:
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 100
    time_horizon: 64
    summary_freq: 50   # Deve logar apenas a cada 50 steps
    keep_checkpoints: 5
env_settings:
  env_path: "/Users/victorbarbosa/git/UNITY Web/UnityMoonLander/Mac/App.app"
  base_port: 5004
torch_settings:
  device: "cpu"  # Mudado para CPU
environment_parameters:
  currentLesson: 5
  maxHorizontal: 4
  steps: 1
